name: Release

on:
  push:
    # branches: 
    #   - 'release/**'

jobs:
  # This workflow contains a single job called "release"
  release:
    name: Build & Deploy to Cloud run
    environment: totolive
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Login to Container Registry
      uses: docker/login-action@v1
      with: 
          registry: eu.gcr.io
          username: _json_key
          password: ${{ secrets.CICD_SERVICE_ACCOUNT }}

    - name: Create Environment Variables
      run: |
        export PACKAGE_VERSION=$(cat package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[",]//g' | tr -d '[[:space:]]')
        export PACKAGE_NAME=$(cat package.json | grep name | head -1 | awk -F: '{ print $2 }' | sed 's/[",]//g' | tr -d '[[:space:]]')
        echo "PACKAGE_NAME=$PACKAGE_NAME" >> $GITHUB_ENV
        echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> $GITHUB_ENV

    - name: Build Docker image
      run: |
        docker build . -t eu.gcr.io/${{ vars.GCP_PID }}/${{env.PACKAGE_NAME}}:${{env.PACKAGE_VERSION}}
 
    - name: Push Docker image to Dockerhub 
      run: |
        docker push eu.gcr.io/${{ vars.GCP_PID }}/${{env.PACKAGE_NAME}}:${{env.PACKAGE_VERSION}}
    
    - name: Setup GCloud 
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ vars.GCP_PID }}
        service_account_key: ${{ secrets.CICD_SERVICE_ACCOUNT }}
        export_default_credentials: true
    
    - name: Deploy image
      run: | 
        gcloud run deploy ${{env.PACKAGE_NAME}} --set-env-vars "GCP_PID=${{ vars.GCP_PIDÂ }},BACKUP_BUCKET=${{ secrets.BACKUP_BUCKET }},GAMES_DATA_BUCKET=${{ secrets.GAMES_BUCKET }},EPXCAT_API_ENDPOINT=${{ secrets.EPXCAT_API_ENDPOINT }},KUD_API_ENDPOINT=${{ secrets.KUD_API_ENDPOINT }},EXPENSES_API_ENDPOINT=${{secrets.EXPENSESV2_API_ENDPOINT}}" --service-account=${{ secrets.SERVICE_ACCOUNT }} --project=${{ vars.GCP_PID }} --image=eu.gcr.io/${{ vars.GCP_PID }}/${{env.PACKAGE_NAME}}:${{env.PACKAGE_VERSION}} --platform=managed --region=europe-west1 --allow-unauthenticated --min-instances 1